# syntax = devthefuture/dockerfile-x:1.4.2

FROM eclipse-temurin:21-jdk-alpine AS build

INCLUDE Dockerfile-standalone.build.base

RUN ./gradlew bootJar


FROM eclipse-temurin:21-jre-alpine
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "app.jar" ]
