# syntax = devthefuture/dockerfile-x:1.4.2

FROM ghcr.io/graalvm/native-image-community:21-muslib AS build

RUN microdnf --setopt=install_weak_deps=0 install -y findutils-4.8.0-7.el9

INCLUDE Dockerfile-standalone.build.base

RUN ./gradlew nativeCompile -PnativeExtraArgs="--libc=musl --static" --no-daemon
