FROM gradle:jdk21-graal AS build
COPY gradlew /code/gradlew
COPY gradle /code/gradle
COPY build.gradle /code/
COPY settings.gradle /code/
WORKDIR /code
RUN ./gradlew --version
COPY src /code/src
RUN ./gradlew nativeCompile

FROM redhat/ubi9-minimal:latest
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --from=build --chown=1001:root /code/build/native/nativeCompile/demo /work/application

EXPOSE 8080
USER 1001
ENTRYPOINT ["./application"]
