# syntax = devthefuture/dockerfile-x:1.4.2

INCLUDE Dockerfile-standalone.native.build.base


FROM scratch AS scratch-dir-supply


FROM scratch

COPY --from=build /app/build/native/nativeCompile/demo /work/application
COPY --from=scratch-dir-supply --chown=1001:1001 / /tmp

INCLUDE Dockerfile-standalone.native.exec.base
