# syntax = devthefuture/dockerfile-x:1.4.2

INCLUDE Dockerfile-standalone.native.build.base


FROM alpine:3.22.1

COPY --from=build /app/build/native/nativeCompile/demo /work/application

INCLUDE Dockerfile-standalone.native.exec.base
