name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Demo on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: ubuntu-24.04-arm
            arch: ARM64
          - os: macos-15
            arch: ARM64
          - os: macos-13
            arch: x64
          - os: windows-2025
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build natively
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            docker run --rm -v $PWD:/work -w /work ghcr.io/graalvm/native-image-community:21-muslib \
              /bin/sh -c "microdnf --setopt=install_weak_deps=0 install -y findutils-4.8.0-7.el9 && ./gradlew nativeCompile -PnativeExtraArgs=\"--libc=musl --static\" --no-daemon"
          else
            ./gradlew nativeCompile --no-daemon
          fi
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.os }}-${{ matrix.arch }}
          path: ./build/native/nativeCompile/*
