name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Demo on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: ARM64
          - os: macos-latest
            arch: ARM64
          - os: macos-13
            arch: x64
          - os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - name: Build natively in case of Linux ARM64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'ARM64'
        run: docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/home/gradle/project -w /home/gradle/project gradle:jdk21-graal ./gradlew nativeCompile
      - name: Setup GraalVM
        if: matrix.os != 'ubuntu-latest' || matrix.arch != 'ARM64'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build natively
        if: matrix.os != 'ubuntu-latest' || matrix.arch != 'ARM64'
        run: ./gradlew nativeCompile
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.os }}-${{ matrix.arch }}
          path: ./build/native/nativeCompile/*
